// Generated by `supabase gen types --lang swift --local --schema xix`, made public by scripts/gen-models.sh. Do not edit.
import Foundation
import Supabase

public enum XixSchema {
  public struct CalloutResponsesSelect: Codable, Hashable, Sendable {
    public let action: String
    public let calloutId: UUID
    public let playerId: UUID
    public let respondedAt: String
    public enum CodingKeys: String, CodingKey {
      case action = "action"
      case calloutId = "callout_id"
      case playerId = "player_id"
      case respondedAt = "responded_at"
    }
  }
  public struct CalloutResponsesInsert: Codable, Hashable, Sendable {
    public let action: String
    public let calloutId: UUID
    public let playerId: UUID
    public let respondedAt: String?
    public enum CodingKeys: String, CodingKey {
      case action = "action"
      case calloutId = "callout_id"
      case playerId = "player_id"
      case respondedAt = "responded_at"
    }
  }
  public struct CalloutResponsesUpdate: Codable, Hashable, Sendable {
    public let action: String?
    public let calloutId: UUID?
    public let playerId: UUID?
    public let respondedAt: String?
    public enum CodingKeys: String, CodingKey {
      case action = "action"
      case calloutId = "callout_id"
      case playerId = "player_id"
      case respondedAt = "responded_at"
    }
  }
  public struct CalloutsSelect: Codable, Hashable, Sendable {
    public let callerId: UUID
    public let closedAt: String?
    public let createdAt: String
    public let hole: Int16
    public let id: UUID
    public let kind: String
    public let params: AnyJSON
    public let roundId: UUID
    public let status: String
    public let targetIds: [UUID]
    public enum CodingKeys: String, CodingKey {
      case callerId = "caller_id"
      case closedAt = "closed_at"
      case createdAt = "created_at"
      case hole = "hole"
      case id = "id"
      case kind = "kind"
      case params = "params"
      case roundId = "round_id"
      case status = "status"
      case targetIds = "target_ids"
    }
  }
  public struct CalloutsInsert: Codable, Hashable, Sendable {
    public let callerId: UUID
    public let closedAt: String?
    public let createdAt: String?
    public let hole: Int16
    public let id: UUID?
    public let kind: String
    public let params: AnyJSON?
    public let roundId: UUID
    public let status: String?
    public let targetIds: [UUID]
    public enum CodingKeys: String, CodingKey {
      case callerId = "caller_id"
      case closedAt = "closed_at"
      case createdAt = "created_at"
      case hole = "hole"
      case id = "id"
      case kind = "kind"
      case params = "params"
      case roundId = "round_id"
      case status = "status"
      case targetIds = "target_ids"
    }
  }
  public struct CalloutsUpdate: Codable, Hashable, Sendable {
    public let callerId: UUID?
    public let closedAt: String?
    public let createdAt: String?
    public let hole: Int16?
    public let id: UUID?
    public let kind: String?
    public let params: AnyJSON?
    public let roundId: UUID?
    public let status: String?
    public let targetIds: [UUID]?
    public enum CodingKeys: String, CodingKey {
      case callerId = "caller_id"
      case closedAt = "closed_at"
      case createdAt = "created_at"
      case hole = "hole"
      case id = "id"
      case kind = "kind"
      case params = "params"
      case roundId = "round_id"
      case status = "status"
      case targetIds = "target_ids"
    }
  }
  public struct ConfirmationsSelect: Codable, Hashable, Sendable {
    public let action: String
    public let createdAt: String
    public let profileId: UUID
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case action = "action"
      case createdAt = "created_at"
      case profileId = "profile_id"
      case roundId = "round_id"
    }
  }
  public struct ConfirmationsInsert: Codable, Hashable, Sendable {
    public let action: String
    public let createdAt: String?
    public let profileId: UUID
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case action = "action"
      case createdAt = "created_at"
      case profileId = "profile_id"
      case roundId = "round_id"
    }
  }
  public struct ConfirmationsUpdate: Codable, Hashable, Sendable {
    public let action: String?
    public let createdAt: String?
    public let profileId: UUID?
    public let roundId: UUID?
    public enum CodingKeys: String, CodingKey {
      case action = "action"
      case createdAt = "created_at"
      case profileId = "profile_id"
      case roundId = "round_id"
    }
  }
  public struct CourseHolesSelect: Codable, Hashable, Sendable {
    public let courseId: UUID
    public let hole: Int16
    public let par: Int16?
    public let strokeIndex: Int16?
    public let yards: Int32?
    public enum CodingKeys: String, CodingKey {
      case courseId = "course_id"
      case hole = "hole"
      case par = "par"
      case strokeIndex = "stroke_index"
      case yards = "yards"
    }
  }
  public struct CourseHolesInsert: Codable, Hashable, Sendable {
    public let courseId: UUID
    public let hole: Int16
    public let par: Int16?
    public let strokeIndex: Int16?
    public let yards: Int32?
    public enum CodingKeys: String, CodingKey {
      case courseId = "course_id"
      case hole = "hole"
      case par = "par"
      case strokeIndex = "stroke_index"
      case yards = "yards"
    }
  }
  public struct CourseHolesUpdate: Codable, Hashable, Sendable {
    public let courseId: UUID?
    public let hole: Int16?
    public let par: Int16?
    public let strokeIndex: Int16?
    public let yards: Int32?
    public enum CodingKeys: String, CodingKey {
      case courseId = "course_id"
      case hole = "hole"
      case par = "par"
      case strokeIndex = "stroke_index"
      case yards = "yards"
    }
  }
  public struct CoursesSelect: Codable, Hashable, Sendable {
    public let createdAt: String
    public let createdBy: UUID?
    public let id: UUID
    public let name: String
    public let osmId: Int64?
    public let region: String?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case createdBy = "created_by"
      case id = "id"
      case name = "name"
      case osmId = "osm_id"
      case region = "region"
    }
  }
  public struct CoursesInsert: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let createdBy: UUID?
    public let id: UUID?
    public let name: String
    public let osmId: Int64?
    public let region: String?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case createdBy = "created_by"
      case id = "id"
      case name = "name"
      case osmId = "osm_id"
      case region = "region"
    }
  }
  public struct CoursesUpdate: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let createdBy: UUID?
    public let id: UUID?
    public let name: String?
    public let osmId: Int64?
    public let region: String?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case createdBy = "created_by"
      case id = "id"
      case name = "name"
      case osmId = "osm_id"
      case region = "region"
    }
  }
  public struct CrewMembersSelect: Codable, Hashable, Sendable {
    public let crewId: UUID
    public let joinedAt: String
    public let profileId: UUID
    public enum CodingKeys: String, CodingKey {
      case crewId = "crew_id"
      case joinedAt = "joined_at"
      case profileId = "profile_id"
    }
  }
  public struct CrewMembersInsert: Codable, Hashable, Sendable {
    public let crewId: UUID
    public let joinedAt: String?
    public let profileId: UUID
    public enum CodingKeys: String, CodingKey {
      case crewId = "crew_id"
      case joinedAt = "joined_at"
      case profileId = "profile_id"
    }
  }
  public struct CrewMembersUpdate: Codable, Hashable, Sendable {
    public let crewId: UUID?
    public let joinedAt: String?
    public let profileId: UUID?
    public enum CodingKeys: String, CodingKey {
      case crewId = "crew_id"
      case joinedAt = "joined_at"
      case profileId = "profile_id"
    }
  }
  public struct CrewsSelect: Codable, Hashable, Sendable {
    public let createdAt: String
    public let id: UUID
    public let name: String
    public let ownerId: UUID
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case id = "id"
      case name = "name"
      case ownerId = "owner_id"
    }
  }
  public struct CrewsInsert: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let id: UUID?
    public let name: String
    public let ownerId: UUID
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case id = "id"
      case name = "name"
      case ownerId = "owner_id"
    }
  }
  public struct CrewsUpdate: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let id: UUID?
    public let name: String?
    public let ownerId: UUID?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case id = "id"
      case name = "name"
      case ownerId = "owner_id"
    }
  }
  public struct EngineDeadLetterSelect: Codable, Hashable, Sendable {
    public let error: String?
    public let failedAt: String
    public let id: UUID
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case error = "error"
      case failedAt = "failed_at"
      case id = "id"
      case roundId = "round_id"
    }
  }
  public struct EngineDeadLetterInsert: Codable, Hashable, Sendable {
    public let error: String?
    public let failedAt: String?
    public let id: UUID?
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case error = "error"
      case failedAt = "failed_at"
      case id = "id"
      case roundId = "round_id"
    }
  }
  public struct EngineDeadLetterUpdate: Codable, Hashable, Sendable {
    public let error: String?
    public let failedAt: String?
    public let id: UUID?
    public let roundId: UUID?
    public enum CodingKeys: String, CodingKey {
      case error = "error"
      case failedAt = "failed_at"
      case id = "id"
      case roundId = "round_id"
    }
  }
  public struct EngineQueueSelect: Codable, Hashable, Sendable {
    public let attempts: Int32
    public let lastError: String?
    public let requestedAt: String
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case attempts = "attempts"
      case lastError = "last_error"
      case requestedAt = "requested_at"
      case roundId = "round_id"
    }
  }
  public struct EngineQueueInsert: Codable, Hashable, Sendable {
    public let attempts: Int32?
    public let lastError: String?
    public let requestedAt: String?
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case attempts = "attempts"
      case lastError = "last_error"
      case requestedAt = "requested_at"
      case roundId = "round_id"
    }
  }
  public struct EngineQueueUpdate: Codable, Hashable, Sendable {
    public let attempts: Int32?
    public let lastError: String?
    public let requestedAt: String?
    public let roundId: UUID?
    public enum CodingKeys: String, CodingKey {
      case attempts = "attempts"
      case lastError = "last_error"
      case requestedAt = "requested_at"
      case roundId = "round_id"
    }
  }
  public struct GamePlayersSelect: Codable, Hashable, Sendable {
    public let gameId: UUID
    public let playerId: UUID
    public let roundId: UUID
    public let side: Int16?
    public enum CodingKeys: String, CodingKey {
      case gameId = "game_id"
      case playerId = "player_id"
      case roundId = "round_id"
      case side = "side"
    }
  }
  public struct GamePlayersInsert: Codable, Hashable, Sendable {
    public let gameId: UUID
    public let playerId: UUID
    public let roundId: UUID
    public let side: Int16?
    public enum CodingKeys: String, CodingKey {
      case gameId = "game_id"
      case playerId = "player_id"
      case roundId = "round_id"
      case side = "side"
    }
  }
  public struct GamePlayersUpdate: Codable, Hashable, Sendable {
    public let gameId: UUID?
    public let playerId: UUID?
    public let roundId: UUID?
    public let side: Int16?
    public enum CodingKeys: String, CodingKey {
      case gameId = "game_id"
      case playerId = "player_id"
      case roundId = "round_id"
      case side = "side"
    }
  }
  public struct GamesSelect: Codable, Hashable, Sendable {
    public let createdAt: String
    public let format: String
    public let id: UUID
    public let options: AnyJSON
    public let position: Int16
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case format = "format"
      case id = "id"
      case options = "options"
      case position = "position"
      case roundId = "round_id"
    }
  }
  public struct GamesInsert: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let format: String
    public let id: UUID?
    public let options: AnyJSON?
    public let position: Int16?
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case format = "format"
      case id = "id"
      case options = "options"
      case position = "position"
      case roundId = "round_id"
    }
  }
  public struct GamesUpdate: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let format: String?
    public let id: UUID?
    public let options: AnyJSON?
    public let position: Int16?
    public let roundId: UUID?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case format = "format"
      case id = "id"
      case options = "options"
      case position = "position"
      case roundId = "round_id"
    }
  }
  public struct MedalsSelect: Codable, Hashable, Sendable {
    public let context: AnyJSON
    public let createdAt: String
    public let id: UUID
    public let key: String
    public let opponentProfileId: UUID?
    public let profileId: UUID
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case context = "context"
      case createdAt = "created_at"
      case id = "id"
      case key = "key"
      case opponentProfileId = "opponent_profile_id"
      case profileId = "profile_id"
      case roundId = "round_id"
    }
  }
  public struct MedalsInsert: Codable, Hashable, Sendable {
    public let context: AnyJSON?
    public let createdAt: String?
    public let id: UUID?
    public let key: String
    public let opponentProfileId: UUID?
    public let profileId: UUID
    public let roundId: UUID
    public enum CodingKeys: String, CodingKey {
      case context = "context"
      case createdAt = "created_at"
      case id = "id"
      case key = "key"
      case opponentProfileId = "opponent_profile_id"
      case profileId = "profile_id"
      case roundId = "round_id"
    }
  }
  public struct MedalsUpdate: Codable, Hashable, Sendable {
    public let context: AnyJSON?
    public let createdAt: String?
    public let id: UUID?
    public let key: String?
    public let opponentProfileId: UUID?
    public let profileId: UUID?
    public let roundId: UUID?
    public enum CodingKeys: String, CodingKey {
      case context = "context"
      case createdAt = "created_at"
      case id = "id"
      case key = "key"
      case opponentProfileId = "opponent_profile_id"
      case profileId = "profile_id"
      case roundId = "round_id"
    }
  }
  public struct PlayersSelect: Codable, Hashable, Sendable {
    public let claimedAt: String?
    public let createdAt: String
    public let displayName: String
    public let id: UUID
    public let leftAt: String?
    public let levelSnapshot: Decimal?
    public let profileId: UUID?
    public let roundId: UUID
    public let seat: Int16
    public enum CodingKeys: String, CodingKey {
      case claimedAt = "claimed_at"
      case createdAt = "created_at"
      case displayName = "display_name"
      case id = "id"
      case leftAt = "left_at"
      case levelSnapshot = "level_snapshot"
      case profileId = "profile_id"
      case roundId = "round_id"
      case seat = "seat"
    }
  }
  public struct PlayersInsert: Codable, Hashable, Sendable {
    public let claimedAt: String?
    public let createdAt: String?
    public let displayName: String
    public let id: UUID?
    public let leftAt: String?
    public let levelSnapshot: Decimal?
    public let profileId: UUID?
    public let roundId: UUID
    public let seat: Int16
    public enum CodingKeys: String, CodingKey {
      case claimedAt = "claimed_at"
      case createdAt = "created_at"
      case displayName = "display_name"
      case id = "id"
      case leftAt = "left_at"
      case levelSnapshot = "level_snapshot"
      case profileId = "profile_id"
      case roundId = "round_id"
      case seat = "seat"
    }
  }
  public struct PlayersUpdate: Codable, Hashable, Sendable {
    public let claimedAt: String?
    public let createdAt: String?
    public let displayName: String?
    public let id: UUID?
    public let leftAt: String?
    public let levelSnapshot: Decimal?
    public let profileId: UUID?
    public let roundId: UUID?
    public let seat: Int16?
    public enum CodingKeys: String, CodingKey {
      case claimedAt = "claimed_at"
      case createdAt = "created_at"
      case displayName = "display_name"
      case id = "id"
      case leftAt = "left_at"
      case levelSnapshot = "level_snapshot"
      case profileId = "profile_id"
      case roundId = "round_id"
      case seat = "seat"
    }
  }
  public struct ProfilesSelect: Codable, Hashable, Sendable {
    public let createdAt: String
    public let displayName: String?
    public let id: UUID
    public let levelAuto: Decimal?
    public let levelIndex: Decimal?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case displayName = "display_name"
      case id = "id"
      case levelAuto = "level_auto"
      case levelIndex = "level_index"
    }
  }
  public struct ProfilesInsert: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let displayName: String?
    public let id: UUID
    public let levelAuto: Decimal?
    public let levelIndex: Decimal?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case displayName = "display_name"
      case id = "id"
      case levelAuto = "level_auto"
      case levelIndex = "level_index"
    }
  }
  public struct ProfilesUpdate: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let displayName: String?
    public let id: UUID?
    public let levelAuto: Decimal?
    public let levelIndex: Decimal?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case displayName = "display_name"
      case id = "id"
      case levelAuto = "level_auto"
      case levelIndex = "level_index"
    }
  }
  public struct RankingEntriesSelect: Codable, Hashable, Sendable {
    public let computedAt: String
    public let metric: String
    public let profileId: UUID
    public let value: Decimal
    public let window: String
    public enum CodingKeys: String, CodingKey {
      case computedAt = "computed_at"
      case metric = "metric"
      case profileId = "profile_id"
      case value = "value"
      case window = "window"
    }
  }
  public struct RankingEntriesInsert: Codable, Hashable, Sendable {
    public let computedAt: String?
    public let metric: String
    public let profileId: UUID
    public let value: Decimal
    public let window: String
    public enum CodingKeys: String, CodingKey {
      case computedAt = "computed_at"
      case metric = "metric"
      case profileId = "profile_id"
      case value = "value"
      case window = "window"
    }
  }
  public struct RankingEntriesUpdate: Codable, Hashable, Sendable {
    public let computedAt: String?
    public let metric: String?
    public let profileId: UUID?
    public let value: Decimal?
    public let window: String?
    public enum CodingKeys: String, CodingKey {
      case computedAt = "computed_at"
      case metric = "metric"
      case profileId = "profile_id"
      case value = "value"
      case window = "window"
    }
  }
  public struct ResultsSelect: Codable, Hashable, Sendable {
    public let computedAt: String
    public let payload: AnyJSON
    public let roundId: UUID
    public let version: Int32
    public enum CodingKeys: String, CodingKey {
      case computedAt = "computed_at"
      case payload = "payload"
      case roundId = "round_id"
      case version = "version"
    }
  }
  public struct ResultsInsert: Codable, Hashable, Sendable {
    public let computedAt: String?
    public let payload: AnyJSON
    public let roundId: UUID
    public let version: Int32
    public enum CodingKeys: String, CodingKey {
      case computedAt = "computed_at"
      case payload = "payload"
      case roundId = "round_id"
      case version = "version"
    }
  }
  public struct ResultsUpdate: Codable, Hashable, Sendable {
    public let computedAt: String?
    public let payload: AnyJSON?
    public let roundId: UUID?
    public let version: Int32?
    public enum CodingKeys: String, CodingKey {
      case computedAt = "computed_at"
      case payload = "payload"
      case roundId = "round_id"
      case version = "version"
    }
  }
  public struct RoundsSelect: Codable, Hashable, Sendable {
    public let countedAt: String?
    public let courseId: UUID?
    public let createdAt: String
    public let endedAt: String?
    public let holes: Int16
    public let id: UUID
    public let joinCode: String
    public let ownerId: UUID
    public let playedOn: String
    public let status: String
    public enum CodingKeys: String, CodingKey {
      case countedAt = "counted_at"
      case courseId = "course_id"
      case createdAt = "created_at"
      case endedAt = "ended_at"
      case holes = "holes"
      case id = "id"
      case joinCode = "join_code"
      case ownerId = "owner_id"
      case playedOn = "played_on"
      case status = "status"
    }
  }
  public struct RoundsInsert: Codable, Hashable, Sendable {
    public let countedAt: String?
    public let courseId: UUID?
    public let createdAt: String?
    public let endedAt: String?
    public let holes: Int16?
    public let id: UUID?
    public let joinCode: String?
    public let ownerId: UUID
    public let playedOn: String?
    public let status: String?
    public enum CodingKeys: String, CodingKey {
      case countedAt = "counted_at"
      case courseId = "course_id"
      case createdAt = "created_at"
      case endedAt = "ended_at"
      case holes = "holes"
      case id = "id"
      case joinCode = "join_code"
      case ownerId = "owner_id"
      case playedOn = "played_on"
      case status = "status"
    }
  }
  public struct RoundsUpdate: Codable, Hashable, Sendable {
    public let countedAt: String?
    public let courseId: UUID?
    public let createdAt: String?
    public let endedAt: String?
    public let holes: Int16?
    public let id: UUID?
    public let joinCode: String?
    public let ownerId: UUID?
    public let playedOn: String?
    public let status: String?
    public enum CodingKeys: String, CodingKey {
      case countedAt = "counted_at"
      case courseId = "course_id"
      case createdAt = "created_at"
      case endedAt = "ended_at"
      case holes = "holes"
      case id = "id"
      case joinCode = "join_code"
      case ownerId = "owner_id"
      case playedOn = "played_on"
      case status = "status"
    }
  }
  public struct ScoresSelect: Codable, Hashable, Sendable {
    public let clientTs: String?
    public let enteredBy: UUID?
    public let hole: Int16
    public let pickedUp: Bool
    public let playerId: UUID
    public let roundId: UUID
    public let strokes: Int16?
    public let updatedAt: String
    public enum CodingKeys: String, CodingKey {
      case clientTs = "client_ts"
      case enteredBy = "entered_by"
      case hole = "hole"
      case pickedUp = "picked_up"
      case playerId = "player_id"
      case roundId = "round_id"
      case strokes = "strokes"
      case updatedAt = "updated_at"
    }
  }
  public struct ScoresInsert: Codable, Hashable, Sendable {
    public let clientTs: String?
    public let enteredBy: UUID?
    public let hole: Int16
    public let pickedUp: Bool?
    public let playerId: UUID
    public let roundId: UUID
    public let strokes: Int16?
    public let updatedAt: String?
    public enum CodingKeys: String, CodingKey {
      case clientTs = "client_ts"
      case enteredBy = "entered_by"
      case hole = "hole"
      case pickedUp = "picked_up"
      case playerId = "player_id"
      case roundId = "round_id"
      case strokes = "strokes"
      case updatedAt = "updated_at"
    }
  }
  public struct ScoresUpdate: Codable, Hashable, Sendable {
    public let clientTs: String?
    public let enteredBy: UUID?
    public let hole: Int16?
    public let pickedUp: Bool?
    public let playerId: UUID?
    public let roundId: UUID?
    public let strokes: Int16?
    public let updatedAt: String?
    public enum CodingKeys: String, CodingKey {
      case clientTs = "client_ts"
      case enteredBy = "entered_by"
      case hole = "hole"
      case pickedUp = "picked_up"
      case playerId = "player_id"
      case roundId = "round_id"
      case strokes = "strokes"
      case updatedAt = "updated_at"
    }
  }
  public struct StickersSelect: Codable, Hashable, Sendable {
    public let createdAt: String
    public let hole: Int16
    public let id: UUID
    public let packKey: String
    public let playedAt: String?
    public let roundId: UUID
    public let senderPlayerId: UUID
    public let stickerKey: String
    public let targetPlayerId: UUID
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case hole = "hole"
      case id = "id"
      case packKey = "pack_key"
      case playedAt = "played_at"
      case roundId = "round_id"
      case senderPlayerId = "sender_player_id"
      case stickerKey = "sticker_key"
      case targetPlayerId = "target_player_id"
    }
  }
  public struct StickersInsert: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let hole: Int16
    public let id: UUID?
    public let packKey: String?
    public let playedAt: String?
    public let roundId: UUID
    public let senderPlayerId: UUID
    public let stickerKey: String
    public let targetPlayerId: UUID
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case hole = "hole"
      case id = "id"
      case packKey = "pack_key"
      case playedAt = "played_at"
      case roundId = "round_id"
      case senderPlayerId = "sender_player_id"
      case stickerKey = "sticker_key"
      case targetPlayerId = "target_player_id"
    }
  }
  public struct StickersUpdate: Codable, Hashable, Sendable {
    public let createdAt: String?
    public let hole: Int16?
    public let id: UUID?
    public let packKey: String?
    public let playedAt: String?
    public let roundId: UUID?
    public let senderPlayerId: UUID?
    public let stickerKey: String?
    public let targetPlayerId: UUID?
    public enum CodingKeys: String, CodingKey {
      case createdAt = "created_at"
      case hole = "hole"
      case id = "id"
      case packKey = "pack_key"
      case playedAt = "played_at"
      case roundId = "round_id"
      case senderPlayerId = "sender_player_id"
      case stickerKey = "sticker_key"
      case targetPlayerId = "target_player_id"
    }
  }
  public struct PublicProfilesSelect: Codable, Hashable, Sendable {
    public let displayName: String?
    public let id: UUID?
    public enum CodingKeys: String, CodingKey {
      case displayName = "display_name"
      case id = "id"
    }
  }
}
