-- Generated by supabase/scripts/gen_seed.py from fraserview_2026-09-09.json. Do not edit by hand.
-- The Fraserview round (2026-09-09) as data: users, course, round, players, scores, games, callouts.
begin;

-- Auth users. Sign in with Apple only: no password and no identity rows here; local sessions for
-- these users are minted from the local JWT secret in tests.
insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', '11111111-1111-4111-8111-111111111111', 'authenticated', 'authenticated', 'ray@privaterelay.appleid.com', now(), '{"provider":"apple","providers":["apple"]}', '{"display_name":"Ray"}'::jsonb, now(), now(), '', '', '', '');
insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', '22222222-2222-4222-8222-222222222222', 'authenticated', 'authenticated', 'dave@privaterelay.appleid.com', now(), '{"provider":"apple","providers":["apple"]}', '{"display_name":"Dave"}'::jsonb, now(), now(), '', '', '', '');
insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', '33333333-3333-4333-8333-333333333333', 'authenticated', 'authenticated', 'mo@privaterelay.appleid.com', now(), '{"provider":"apple","providers":["apple"]}', '{"display_name":"Mo"}'::jsonb, now(), now(), '', '', '', '');
insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', '44444444-4444-4444-8444-444444444444', 'authenticated', 'authenticated', 'tess@privaterelay.appleid.com', now(), '{"provider":"apple","providers":["apple"]}', '{"display_name":"Tess"}'::jsonb, now(), now(), '', '', '', '');

-- Profiles; Level (auto) is the fixture's level for each player.
insert into xix.profiles (id, display_name, level_auto) values ('11111111-1111-4111-8111-111111111111', 'Ray', 5);
insert into xix.profiles (id, display_name, level_auto) values ('22222222-2222-4222-8222-222222222222', 'Dave', 4);
insert into xix.profiles (id, display_name, level_auto) values ('33333333-3333-4333-8333-333333333333', 'Mo', 3);
insert into xix.profiles (id, display_name, level_auto) values ('44444444-4444-4444-8444-444444444444', 'Tess', 5);

-- Course
insert into xix.courses (id, name, region, created_by) values ('55555555-5555-4555-8555-555555555555', 'Fraserview', 'Vancouver', '11111111-1111-4111-8111-111111111111');
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 1, 4, 7);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 2, 3, 15);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 3, 5, 1);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 4, 4, 9);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 5, 4, 5);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 6, 3, 17);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 7, 4, 11);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 8, 5, 3);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 9, 4, 13);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 10, 4, 8);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 11, 5, 2);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 12, 4, 10);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 13, 4, 4);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 14, 4, 12);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 15, 3, 18);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 16, 4, 6);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 17, 5, 14);
insert into xix.course_holes (course_id, hole, par, stroke_index) values ('55555555-5555-4555-8555-555555555555', 18, 3, 16);

-- Round, ended the same afternoon
insert into xix.rounds (id, owner_id, course_id, played_on, holes, status, join_code, ended_at, created_at)
values ('66666666-6666-4666-8666-666666666666', '11111111-1111-4111-8111-111111111111', '55555555-5555-4555-8555-555555555555', '2026-09-09', 18, 'ended', 'FRSRVW', '2026-09-09 16:30:00-07', '2026-09-09 12:00:00-07');

-- Players in seat order, all claimed
insert into xix.players (id, round_id, profile_id, display_name, seat, level_snapshot, claimed_at)
values ('77777777-7777-4777-8777-777777777771', '66666666-6666-4666-8666-666666666666', '11111111-1111-4111-8111-111111111111', 'Ray', 0, 5, '2026-09-09 12:05:00-07');
insert into xix.players (id, round_id, profile_id, display_name, seat, level_snapshot, claimed_at)
values ('77777777-7777-4777-8777-777777777772', '66666666-6666-4666-8666-666666666666', '22222222-2222-4222-8222-222222222222', 'Dave', 1, 4, '2026-09-09 12:05:00-07');
insert into xix.players (id, round_id, profile_id, display_name, seat, level_snapshot, claimed_at)
values ('77777777-7777-4777-8777-777777777773', '66666666-6666-4666-8666-666666666666', '33333333-3333-4333-8333-333333333333', 'Mo', 2, 3, '2026-09-09 12:05:00-07');
insert into xix.players (id, round_id, profile_id, display_name, seat, level_snapshot, claimed_at)
values ('77777777-7777-4777-8777-777777777774', '66666666-6666-4666-8666-666666666666', '44444444-4444-4444-8444-444444444444', 'Tess', 3, 5, '2026-09-09 12:05:00-07');

-- Games and their players
insert into xix.games (id, round_id, format, options) values ('88888888-8888-4888-8888-888888888881', '66666666-6666-4666-8666-666666666666', 'nassau', '{"net":false,"presses":false}'::jsonb);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888881', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', null);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888881', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', null);
insert into xix.games (id, round_id, format, options) values ('88888888-8888-4888-8888-888888888882', '66666666-6666-4666-8666-666666666666', 'skins', '{"net":false,"carryover":true,"validation":false}'::jsonb);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888882', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', null);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888882', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', null);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888882', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', null);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888882', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', null);
insert into xix.games (id, round_id, format, options) values ('88888888-8888-4888-8888-888888888883', '66666666-6666-4666-8666-666666666666', 'stableford', '{"net":false}'::jsonb);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888883', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', null);
insert into xix.game_players (game_id, round_id, player_id, side) values ('88888888-8888-4888-8888-888888888883', '66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', null);

-- Callouts with per-target responses, before any score so the triggers derive closed_at and status
insert into xix.callouts (id, round_id, hole, kind, caller_id, target_ids, params, created_at)
values ('99999999-9999-4999-8999-999999999991', '66666666-6666-4666-8666-666666666666', 8, 'target', '77777777-7777-4777-8777-777777777771', array['77777777-7777-4777-8777-777777777772']::uuid[], '{"goal":"par"}'::jsonb, '2026-09-09 12:10:00-07');
insert into xix.callout_responses (callout_id, player_id, action) values ('99999999-9999-4999-8999-999999999991', '77777777-7777-4777-8777-777777777772', 'signed');
insert into xix.callouts (id, round_id, hole, kind, caller_id, target_ids, params, created_at)
values ('99999999-9999-4999-8999-999999999992', '66666666-6666-4666-8666-666666666666', 12, 'target', '77777777-7777-4777-8777-777777777771', array['77777777-7777-4777-8777-777777777772']::uuid[], '{"goal":"par"}'::jsonb, '2026-09-09 12:10:00-07');
insert into xix.callout_responses (callout_id, player_id, action) values ('99999999-9999-4999-8999-999999999992', '77777777-7777-4777-8777-777777777772', 'ducked');

-- Scores, entered by the owner in hole order; client_ts advances one minute per hole
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 1, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:15:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 1, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:15:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 1, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:15:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 1, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:15:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 2, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:16:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 2, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:16:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 2, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:16:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 2, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:16:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 3, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:17:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 3, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:17:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 3, 7, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:17:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 3, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:17:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 4, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:18:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 4, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:18:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 4, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:18:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 4, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:18:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 5, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:19:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 5, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:19:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 5, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:19:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 5, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:19:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 6, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:20:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 6, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:20:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 6, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:20:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 6, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:20:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 7, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:21:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 7, 7, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:21:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 7, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:21:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 7, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:21:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 8, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:22:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 8, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:22:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 8, 7, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:22:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 8, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:22:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 9, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:23:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 9, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:23:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 9, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:23:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 9, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:23:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 10, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:24:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 10, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:24:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 10, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:24:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 10, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:24:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 11, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:25:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 11, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:25:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 11, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:25:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 11, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:25:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 12, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:26:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 12, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:26:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 12, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:26:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 12, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:26:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 13, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:27:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 13, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:27:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 13, null, true, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:27:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 13, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:27:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 14, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:28:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 14, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:28:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 14, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:28:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 14, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:28:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 15, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:29:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 15, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:29:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 15, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:29:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 15, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:29:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 16, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:30:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 16, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:30:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 16, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:30:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 16, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:30:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 17, 6, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:31:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 17, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:31:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 17, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:31:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 17, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:31:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777771', 18, 5, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:32:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777772', 18, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:32:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777773', 18, 3, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:32:00-07');
insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values ('66666666-6666-4666-8666-666666666666', '77777777-7777-4777-8777-777777777774', 18, 4, false, '11111111-1111-4111-8111-111111111111', '2026-09-09 12:32:00-07');

commit;
