#!/usr/bin/env python3
"""Generate supabase/seed.sql from the Fraserview fixture (repo root fraserview_2026-09-09.json).

The seed is the round "as data": four auth users, the course with par and stroke index, the
ended round, four claimed player rows, every score, the three games, and the two callouts with
their per-target responses. Callouts and responses are inserted before scores so the triggers
derive closed_at and status exactly as they would in a live round.
"""
import json, pathlib, uuid

root = pathlib.Path(__file__).resolve().parents[2]
fx = json.load(open(root / "fraserview_2026-09-09.json"))
inp = fx["input"]

IDS = {
    "profile": {"ray": "11111111-1111-4111-8111-111111111111", "dave": "22222222-2222-4222-8222-222222222222",
                "mo": "33333333-3333-4333-8333-333333333333", "tess": "44444444-4444-4444-8444-444444444444"},
    "course": "55555555-5555-4555-8555-555555555555",
    "round": "66666666-6666-4666-8666-666666666666",
    "player": {"ray": "77777777-7777-4777-8777-777777777771", "dave": "77777777-7777-4777-8777-777777777772",
               "mo": "77777777-7777-4777-8777-777777777773", "tess": "77777777-7777-4777-8777-777777777774"},
    "game": {"g_nassau": "88888888-8888-4888-8888-888888888881", "g_skins": "88888888-8888-4888-8888-888888888882",
             "g_stab": "88888888-8888-4888-8888-888888888883"},
    "callout": {"c8": "99999999-9999-4999-8999-999999999991", "c12": "99999999-9999-4999-8999-999999999992"},
}
NAMES = {"ray": "Ray", "dave": "Dave", "mo": "Mo", "tess": "Tess"}
PLAYED_ON = "2026-09-09"

def q(s): return "'" + str(s).replace("'", "''") + "'"
def jsonlit(o): return q(json.dumps(o, separators=(",", ":"))) + "::jsonb"

def main():
    global out, w
    out = []
    w = out.append
    w("-- Generated by supabase/scripts/gen_seed.py from fraserview_2026-09-09.json. Do not edit by hand.")
    w("-- The Fraserview round (2026-09-09) as data: users, course, round, players, scores, games, callouts.")
    w("begin;")
    w("")
    w("-- Auth users. Sign in with Apple only: no password and no identity rows here; local sessions for")
    w("-- these users are minted from the local JWT secret in tests.")
    for pid, name in NAMES.items():
        uid = IDS["profile"][pid]
        w(f"insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, "
          f"created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)\n"
          f"values ('00000000-0000-0000-0000-000000000000', {q(uid)}, 'authenticated', 'authenticated', {q(pid + '@privaterelay.appleid.com')}, now(), "
          f"'{{\"provider\":\"apple\",\"providers\":[\"apple\"]}}', {jsonlit({'display_name': name})}, now(), now(), '', '', '', '');")
    w("")
    w("-- Profiles; Level (auto) is the fixture's level for each player.")
    for pid, name in NAMES.items():
        lvl = next(p for p in inp["players"] if p["id"] == pid).get("level")
        w(f"insert into xix.profiles (id, display_name, level_auto) values ({q(IDS['profile'][pid])}, {q(name)}, {lvl});")
    w("")
    w("-- Course")
    w(f"insert into xix.courses (id, name, region, created_by) values ({q(IDS['course'])}, 'Fraserview', 'Vancouver', {q(IDS['profile']['ray'])});")
    for h in range(inp["holes"]):
        par = inp["par"][h]; si = inp["strokeIndex"][h]
        w(f"insert into xix.course_holes (course_id, hole, par, stroke_index) values ({q(IDS['course'])}, {h+1}, "
          f"{'null' if par is None else par}, {'null' if si is None else si});")
    w("")
    w("-- Round, ended the same afternoon")
    w(f"insert into xix.rounds (id, owner_id, course_id, played_on, holes, status, join_code, ended_at, created_at)\n"
      f"values ({q(IDS['round'])}, {q(IDS['profile']['ray'])}, {q(IDS['course'])}, {q(PLAYED_ON)}, {inp['holes']}, 'ended', 'FRSRVW', "
      f"'{PLAYED_ON} 16:30:00-07', '{PLAYED_ON} 12:00:00-07');")
    w("")
    w("-- Players in seat order, all claimed")
    for seat, p in enumerate(inp["players"]):
        pid = p["id"]
        w(f"insert into xix.players (id, round_id, profile_id, display_name, seat, level_snapshot, claimed_at)\n"
          f"values ({q(IDS['player'][pid])}, {q(IDS['round'])}, {q(IDS['profile'][pid])}, {q(NAMES[pid])}, {seat}, "
          f"{p.get('level', 'null')}, '{PLAYED_ON} 12:05:00-07');")
    w("")
    w("-- Games and their players")
    for g in inp["games"]:
        w(f"insert into xix.games (id, round_id, format, options) values ({q(IDS['game'][g['id']])}, {q(IDS['round'])}, "
          f"{q(g['format'])}, {jsonlit(g.get('options', {}))});")
        for pid in g["players"]:
            side = (g.get("sides") or {}).get(pid)
            w(f"insert into xix.game_players (game_id, round_id, player_id, side) values ({q(IDS['game'][g['id']])}, "
              f"{q(IDS['round'])}, {q(IDS['player'][pid])}, {'null' if side is None else side});")
    w("")
    w("-- Callouts with per-target responses, before any score so the triggers derive closed_at and status")
    for c in inp["callouts"]:
        targets = ", ".join(q(IDS["player"][t]) for t in c["targets"])
        w(f"insert into xix.callouts (id, round_id, hole, kind, caller_id, target_ids, params, created_at)\n"
          f"values ({q(IDS['callout'][c['id']])}, {q(IDS['round'])}, {c['hole']}, {q(c['kind'])}, {q(IDS['player'][c['caller']])}, "
          f"array[{targets}]::uuid[], {jsonlit(c.get('params', {}))}, '{PLAYED_ON} 12:10:00-07');")
        for t, action in c.get("responses", {}).items():
            w(f"insert into xix.callout_responses (callout_id, player_id, action) values ({q(IDS['callout'][c['id']])}, "
              f"{q(IDS['player'][t])}, {q(action)});")
    w("")
    w("-- Scores, entered by the owner in hole order; client_ts advances one minute per hole")
    for h in range(inp["holes"]):
        for pid in NAMES:
            s = inp["scores"][pid][h]
            if s is None:
                continue
            picked = isinstance(s, str)
            strokes = "null" if picked else s
            ts = f"'{PLAYED_ON} 12:{15 + h:02d}:00-07'"
            w(f"insert into xix.scores (round_id, player_id, hole, strokes, picked_up, entered_by, client_ts) values "
              f"({q(IDS['round'])}, {q(IDS['player'][pid])}, {h+1}, {strokes}, {'true' if picked else 'false'}, "
              f"{q(IDS['profile']['ray'])}, {ts});")
    w("")
    w("commit;")
    (root / "supabase" / "seed.sql").write_text("\n".join(out) + "\n")
    print(f"wrote supabase/seed.sql ({len(out)} lines)")

if __name__ == "__main__":
    main()
