#!/bin/sh
# Writes XIX/Config/Shared.xcconfig from the linked project's anon key via the Supabase CLI. The key is
# never printed. Run once per machine, and again if the key is rotated.
set -e
cd "$(dirname "$0")/.."
REF=${XIX_PROJECT_REF:-zsipifaskpupjwfiinen}
KEY=$(supabase projects api-keys --project-ref "$REF" -o json 2>/dev/null | python3 -c 'import json,sys; ks=json.load(sys.stdin); print(next(k["api_key"] for k in ks if k["id"]=="anon"))')
[ -n "$KEY" ] || { echo "no anon key from the CLI; run supabase login first" >&2; exit 1; }
{
  echo "// Generated by scripts/gen-xcconfig.sh; not committed."
  echo "XIX_SHARED_URL = https:/\$()/$REF.supabase.co"
  echo "XIX_SHARED_ANON_KEY = $KEY"
} > XIX/Config/Shared.xcconfig
printf 'window.XIX = { url: "https://%s.supabase.co", anonKey: "%s" };\n' "$REF" "$KEY" > web/config.js
echo "wrote XIX/Config/Shared.xcconfig and web/config.js"
