#!/usr/bin/env bash
# Regenerate XIXModels/Sources/XIXModels/Generated.swift from the local database (run after a migration).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/XIXModels/Sources/XIXModels/Generated.swift"
{
  echo "// Generated by \`supabase gen types --lang swift --local --schema xix\`, made public by scripts/gen-models.sh. Do not edit."
  supabase gen types --lang swift --local --schema xix | sed -e 's/^internal /public /; s/^  internal /  public /; s/^    internal /    public /'
} > "$OUT"
echo "wrote $OUT"
